export const levelsData = [{
    "level":"Bob-omb Battlefield",
    "stars": ["Big Bob-omb on the Summit",
    "Footrace with Koopa the Quick",
    "Shoot to the Island in the Sky",
    "Find the 8 Red Coins",
    "Mario Wings to the Sky",
    "Behind Chain Chomp’s Gate",
    "100 Coins Star"],
    "image":"/bob.jpg",
 },{
    "level":"Whomp’s Fortress",
    "stars": ["Chip off Whomp’s Block",
    "To the Top of the Fortress",
    "Shoot into the Wild Blue",
    "Red Coins on the Floating Isle",
    "Fall onto the Caged Island",
    "Blast Away the Wall",
    "100 Coins Star"],
    "image":"",
 },{
    "level":"Jolly Roger Bay",
    "stars": ["Plunder in the Sunken Ship",
    "Can the Eel Come out and Play?",
    "Treasure of the Ocean Cave",
    "Red Coins on the Ship Afloat",
    "Blast to the Stone Pillar",
    "Through the Jet Stream",
    "100 Coins Star"],
    "image":"",
 },{
    "level":"Cool, Cool Mountain",
    "stars": ["Slip Slidin’ Away",
    "Li’l Penguin Lost",
    "Big Penguin Race",
    "Frosty Slide for 8 Red Coins",
    "Snowman’s Lost his Head",
    "Wall Kicks will Work",
    "100 Coins Star"],
    "image":"",
 },{
    "level":"Big Boo’s Haunt",
    "stars": [
     "Go on a Ghost Hunt",
     "Ride Big Boo’s Merry-Go-Round",
     "Secret of the Haunted Books",
     "Seek the 8 Red Coins",
     "Big Boo’s Balcony",
     "Eye to Eye in the Secret Room",
     "100 Coins Star"],
    "image":"",
 },{
    "level":"Hazy Maze Cave",
    "stars": ["Swimming Beast in the Cavern",
    "Elevate for 8 Red Coins",
    "Metal-Head Mario Can Move!",
    "Navigating the Toxic Maze",
    "A-Maze-ing Emergency Exit",
    "Watch for the Rolling Rocks",
    "100 Coins Star"],
    "image":"",
 },{
    "level":"Lethal Lava Land",
    "stars": ["Boil the Big Bully",
    "Bully the Bullies",
    "8-Coin Puzzle with 15 Pieces",
    "Red-Hot Log Rolling",
    "Hot-Foot-It into the Volcano",
    "Elevator Tour in the Volcano",
    "100 Coins Star"],
    "image":"",
 },{
    "level":"Shifting Sand Land",
    "stars": ["In the Talons of the Big Bird",
    "Shining Atop the Pyramid",
    "Inside the Ancient Pyramid",
    "Stand Tall on the Four Pillars",
    "Free Flying for 8 Red Coins",
    "Pyramid Puzzle",
    "100 Coins Star"],
    "image":"",
 },{
    "level":"Dire, Dire Docks",
    "stars": ["Board Bowser’s Sub",
    "Chests in the Current",
    "Pole-Jumping for Red Coins",
    "Through the Jet Stream",
    "The Manta Ray’s Reward",
    "Collect the Caps",
    "100 Coins Star"],
    "image":"",
 },{
    "level":"Snowman’s Land",
    "stars": ["Snowman’s Big Head",
    "Chill with the Bully",
    "In the Deep Freeze",
    "Whirl from the Freezing Pond",
    "Shell Shreddin’ for 8 Red Coins",
    "Into the Igloo",
    "100 Coins Star"],
    "image":"",
 },{
    "level":"Wet-Dry World",
    "stars": [
     "Shocking Arrow Lifts!",
     "Top O’ The Town",
     "Secrets in the Shallows & Sky",
     "Express Elevators–Hurry Up!",
     "Go to Town for Red Coins",
     "Quick Race through Downtown",
     "100 Coins Star"],
    "image":"",
 },{
    "level":"Tall, Tall Mountain",
    "stars": [
     "Scale the Mountain",
     "Mystery of the Monkey Cage",
     "Scary ‘Shrooms, Red Coins",
     "Mysterious Mountainside",
     "Breathtaking View from Bridge",
     "Blast to the Lonely Mushroom",
     "100 Coins Star"],
    "image":"",
 },{
    "level":"Tiny-Huge Island",
    "stars": ["Pluck the Piranha Flower",
    "The Tip Top of the Huge Island",
    "Rematch with Koopa the Quick",
    "Five Itty Bitty Secrets",
    "Wiggler’s Red Coins",
    "Make Wiggler Squirm",
    "100 Coins Star"],
    "image":"",
 },{
    "level":"Tick Tock Clock",
    "stars": [
     "Roll into the Cage",
     "The Pit and the Pendulums",
     "Get a Hand",
     "Stomp on the Thwomp",
     "Timed Jumps on Moving Bars",
     "Stop Time for Red Coins",
     "100 Coins Star"],
    "image":"",
 },{
    "level":"Rainbow Ride",
    "stars": ["Cruiser Crossing the Rainbow",
    "The Big House in the Sky",
    "Coins Amassed in a Maze",
    "Swingin’ in the Breeze",
    "Tricky Triangles!",
    "Somewhere over the Rainbow",
    "100 Coins Star"],
    "image":"",
 },{
    "level":"Castle Secret Stars",
    "stars": ["The Princess’s Secret Slide",
    "The Princess’s Secret Slide (Return)",
    "The Secret Aquarium",
    "Toad’s First Star",
    "Toad’s Second Star",
    "Toad’s Third Star",
    "MIPS Bunny Chase",
    "MIPS Bunny Chase (Again)",
    "Tower of the Wing Cap",
    "Cavern of the Metal Cap",
    "Vanish Cap Under the Moat",
    "Wing Mario Over the Rainbow",
    "Bowser in the Dark World",
    "Bowser in the Fire Sea",
    "Bowser in the Sky"],
    "image":"",
 }];